# Service Configuration
spring.application.name=SymptomChecker-Service
server.port=8087
logging.level.root=INFO
logging.level.com.healthcare=DEBUG

# Hugging Face Configuration
huggingface.api.key=${HUGGINGFACE_API_KEY}
huggingface.model=gpt2
